name: CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  windows-vs22:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update submodules
        run: git submodule update --init --depth 1
      - name: configure
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_CXX_STANDARD=23
#      - name: build debug
#        run: cmake --build build --config=Debug
      - name: build release
        run: cmake --build build --config=Release
      - name: test debug
        run: cd build; ctest -C Debug
      - name: test release
        run: cd build; ctest -C Release
  
  ubuntu-clang-tidy:
    name: Ubuntu Clang-Tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update submodules
        run: git submodule update --init --depth 1
      - name: Install Clang-Tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy
      - name: Run Clang-Tidy
        run: |
          clang-tidy **/*.cpp -- -Iinclude
