name: CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  windows-vs22:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure
        run: cmake -S . --preset=MsvcNinjaRelease -B build
#      - name: build debug
#        run: cmake --build build --config=Debug
      - name: build release
        run: cmake --build build --config=Release
      - name: test debug
        run: cd build; ctest -C Debug
      - name: test release
        run: cd build; ctest -C Release
  windows-clang:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: init
        run: choco install ninja
      - name: install LLVM 20
        run: choco install llvm --version=20.0.0
      - name: configure
        run: cmake -S . --preset=ClangClNinjaRelease -B build
      - name: build debug
 #       run: cmake --build build --config=Debug
 #     - name: build release
        run: cmake --build build --config=Release
      - name: test debug
        run: cd build; ctest -C Debug
      - name: test release
        run: cd build; ctest -C Release

  windows-clang-22:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: init
        run: choco install ninja
      - name: install LLVM 22
        run: choco install llvm --version=22.0.0
      - name: configure
        run: cmake -S . --preset=ClangClNinjaRelease -B build
      - name: build debug
#        run: cmake --build build --config=Debug
#      - name: build release
        run: cmake --build build --config=Release
      - name: test debug
        run: cd build; ctest -C Debug
      - name: test release
        run: cd build; ctest -C Release

  ubuntu-clang-tidy:
    name: Ubuntu Clang-Tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Clang-Tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy
      - name: Run Clang-Tidy
        run: |
          clang-tidy **/*.cpp -- -Iinclude
