name: CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  windows-vs22:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update submodules
        run: git submodule update --init --depth 1
      - name: configure
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_CXX_STANDARD=23
#      - name: build debug
#        run: cmake --build build --config=Debug
      - name: build release
        run: cmake --build build --config=Release
      - name: test debug
        run: cd build; ctest -C Debug
      - name: test release
        run: cd build; ctest -C Release
  windows-clang-20:
    name: Windows Clang-CL 20
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: install ninja
        run: choco install ninja
      - name: install LLVM 20
        run: choco install llvm --version=20.1.8
      - name: configure
        run: cmake -S . --preset=ClangClNinjaRelease -B build
      - name: build debug
        run: cmake --build build --config=Debug
      - name: build release
        run: cmake --build build --config=Release
      - name: test debug
        run: cd build && ctest -C Debug
      - name: test release
        run: cd build && ctest -C Release

  windows-clang-tidy:
    name: Windows Clang-Tidy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update submodules
        run: git submodule update --init --depth 1

      - name: Run clang-tidy
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path Boot\*.cpp, Kernel\*.cpp
          foreach ($file in $files) {
              clang-tidy -std=c++23 $file.FullName -- `
                -I"${{ github.workspace }}\include" `
                -I"${{ github.workspace }}\extern\edk2\MdePkg\Include" `
                -I"${{ github.workspace }}\extern\edk2\MdePkg\Include\X64" `
                -I"${{ github.workspace }}\extern\edk2\MdePkg\Include\Uefi"
          }
